### ISSUE TITLE
Error while loading a main app

### ISSUE THREAD

**Issue by btrice** [dncomponents/dnnorthwind#1]
Hi,
Thank you for your work. i'am just starting to test the dnnorthwind project to familiaryse my self with dncomponents. 
I got some error when i launched the web page. 

`Throwable.java:117 Uncaught Error: java.lang.IllegalStateException: Can't find corresponding binder for com.dncomponents.northwind.MainApp.`

How can i fix this error ? Have you yet occured this error.

Thank your for your reply.

**Comment by nikolasav** [comment]
Hi,
Each Java/Html pair has its generated binder java file on compile. 
So **MainApp.java** should have **MainAppBinder.java** in the same package on the path:

  `dnnorthwind/dnnorthwind-client/target/generated-sources/annotations/com/dncomponents/northwind/MainAppBinder.java`

It seems that you are missing this file from some reason. 

From the root dir try:

`mvn clean compile
`

And re-check if there are corresponding java files in generated folder like on pic:

<img width="491" alt="dn_scr1" src="https://user-images.githubusercontent.com/6130028/135784881-cd32465d-2c53-4333-94c6-3d4c0eb13f6a.png">

Then as usual, in separate windows :

`mvn gwt:codeserver`

And 

`mvn spring-boot:run`

**Comment by btrice** [comment]
Hi @nikolasav ,

You right, i got some error while compiling the project. Especially on each file that end with .html

`java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/dnnorthwind-master/dnnorthwind-client/src/main/java/com/dncomponents/northwind/MainApp.html
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at com.dncomponents.TemplateProcessor.readHtmlPair(TemplateProcessor.java:213)`

I'll find a way to fix it. Thank you for your help.

Therefore i am closing this issues.
