### ISSUE TITLE
Build Fails after fresh clone of repository: client not compiling

### ISSUE THREAD

**Issue by dsissoko** [dncomponents/dnnorthwind#2]
Maven home: /mnt/c/bin/apache-maven-3.8.6
Java version: 17.0.4, vendor: Debian, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.10.16.3-microsoft-standard-wsl2", arch: "amd64", family: "unix"

git clone https://github.com/dncomponents/dnnorthwind.git
cd  dnnorthwind/
mvn gwt:codeserver fails with output:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project dnnorthwind-client: Fatal error compiling: java.lang.IllegalAccessError: class com.dncomponents.TemplateProcessor (in unnamed module @0x7f353a0f) cannot access class com.sun.tools.javac.code.Type$ClassType (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x7f353a0f -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :dnnorthwind-client

**Comment by nikolasav** [comment]
Doesn't work with Java higher than 11.

**Comment by dsissoko** [comment]
> Doesn't work with Java higher than 11.

OK, thanks so much i just arrived to client side development and i cannot give up about the idea to code web client with proper java framework. dncomponents seems promising but i guess its not active enough to update all of this old versions.
anyway thanks and keep faith
